config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'web/reports#index'


  devise_for :users, constraints: {format: :html}, controllers: { registrations: "web/registrations" }
  as :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'

    get 'sign_up', to: 'web/registrations#new'
    get 'cancel',  to: 'web/registrations#cancel'
  end

  namespace :web, defaults: {format: :html}, constraints: {format: :html}, path: '/' do
    root 'reports#index'
    resources :votes,       constraints: {format: :html}
    resources :reports,     constraints: {format: :html}
    resources :issues,      constraints: {format: :html}
    resources :departments, constraints: {format: :html}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [:index, :show]
  end  


  namespace :api, defaults: {format: :json}, constraints: {format: :json}, path: '/api' do
    scope module: :v1 do
  		resources :departments
      resources :issues
      resources :reports
      resources :sessions, only: [:create, :destroy]
      resources :users,    only: [:index, :show]
      resources :votes

    end
  end


end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :department
	has_many :reports
end

app/controllers/api/v1/issues_controller.rb
class Api::V1::IssuesController < ApplicationController
  include Authenticable
  skip_before_action :verify_authenticity_token
  before_action :authenticate_with_token!, only: [:create, :update, :destroy]
  before_action :set_issue, only: [:show, :update, :destroy]
  respond_to :json

  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1.json
  def show
  end

  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      render :show, status: :created, location: api_issue_url(@issue)
    else
      render json: @issue.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /issues/1.json
  def update
    if @issue.update(issue_params)
      render :show, status: :ok, location: api_issue_url(@issue)
    else
      render json: @issue.errors, status: :unprocessable_entity
    end
  end

  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:description, :department_id)
    end
end

app/controllers/web/issues_controller.rb
class Web::IssuesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  layout 'web/layouts/application'
  respond_to :html

  # GET /issues
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  def create
    if user_signed_in?
      @issue = Issue.new(issue_params)
      if @issue.save
        redirect_to web_issue_path(@issue), notice: 'Issue was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /issues/1
  def update
    if user_signed_in?
      if @issue.update(issue_params)
        redirect_to web_issue_path(@issue), notice: 'Issue was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /issues/1
  def destroy
    if user_signed_in?
      @issue.destroy
      redirect_to web_issues_url, notice: 'Issue was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:description, :department_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/web/issues/_form.html.erb
<%= form_for [:web, issue] do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :department %>
    <%= f.select :department_id, Department.all.collect {|c| [ c.name, c.id ] } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web/issues/edit.html.erb
<h1 class="text-center">Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', web_issue_path(@issue) %> |
<%= link_to 'Back', web_issues_path %>

app/views/web/issues/index.html.erb
<h1 class="text-center">Issues</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.description %></td>
        <td><%= issue.department.name %></td>
        <td><%= link_to 'Show', web_issue_path(issue) %></td>
        <td><%= link_to 'Edit', edit_web_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', web_issue_path(issue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_web_issue_path %>

app/views/web/issues/new.html.erb
<h1 class="text-center">New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', web_issues_path %>

app/views/web/issues/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @issue.department.name %>
</p>

<%= link_to 'Edit', edit_web_issue_path(@issue) %> |
<%= link_to 'Back', web_issues_path %>