config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'web/reports#index'


  devise_for :users, constraints: {format: :html}, controllers: { registrations: "web/registrations" }
  as :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'

    get 'sign_up', to: 'web/registrations#new'
    get 'cancel',  to: 'web/registrations#cancel'
  end

  namespace :web, defaults: {format: :html}, constraints: {format: :html}, path: '/' do
    root 'reports#index'
    resources :votes,       constraints: {format: :html}
    resources :reports,     constraints: {format: :html}
    resources :issues,      constraints: {format: :html}
    resources :departments, constraints: {format: :html}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [:index, :show]
  end  


  namespace :api, defaults: {format: :json}, constraints: {format: :json}, path: '/api' do
    scope module: :v1 do
  		resources :departments
      resources :issues
      resources :reports
      resources :sessions, only: [:create, :destroy]
      resources :users,    only: [:index, :show]
      resources :votes

    end
  end


end

app/views/web/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Community</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Last compiled and minified JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href="/">Smart Community</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Reports', web_reports_path %></li>
              <li><%= link_to 'Users', web_users_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %></a></li>
                <li><%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %></li>
                <li>
                    <%= link_to raw("<span class='glyphicon glyphicon-log-out'></span> Logout"), logout_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to raw("<span class='glyphicon glyphicon-log-in'></span> Log in"), login_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <br>
    </header>
  	<% if notice %>
  	  <p class="alert alert-success"><%= notice %></p>
  	<% end %>
   	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %> 	
    <%= yield %>
  </body>
</html>