config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'web/reports#index'


  devise_for :users, constraints: {format: :html}, controllers: { registrations: "web/registrations" }
  as :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'

    get 'sign_up', to: 'web/registrations#new'
    get 'cancel',  to: 'web/registrations#cancel'
  end

  namespace :web, defaults: {format: :html}, constraints: {format: :html}, path: '/' do
    root 'reports#index'
    resources :votes,       constraints: {format: :html}
    resources :reports,     constraints: {format: :html}
    resources :issues,      constraints: {format: :html}
    resources :departments, constraints: {format: :html}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [:index, :show]
  end  


  namespace :api, defaults: {format: :json}, constraints: {format: :json}, path: '/api' do
    scope module: :v1 do
  		resources :departments
      resources :issues
      resources :reports
      resources :sessions, only: [:create, :destroy]
      resources :users,    only: [:index, :show]
      resources :votes

    end
  end


end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :report
	belongs_to :user
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  include Authenticable
  skip_before_action :verify_authenticity_token
  before_action :authenticate_with_token!, only: [:create, :update, :destroy]
  before_action :set_vote, only: [:show, :update, :destroy]
  respond_to :json

  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1.json
  def show
  end

  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      render :show, status: :created, location: api_vote_url(@vote) 
    else
      render json: @vote.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /votes/1.json
  def update
    if @vote.update(vote_params)
      render :show, status: :ok, location: api_vote_url(@vote)
    else
      render json: @vote.errors, status: :unprocessable_entity
    end
  end

  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    head :no_content 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:report_id, :user_id, :direction)
    end
end

app/controllers/web/votes_controller.rb
class Web::VotesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_vote, only: [:show, :edit, :update, :destroy]
  layout 'web/layouts/application'
  respond_to :html

  # GET /votes
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  def create
    if user_signed_in?
      @vote = Vote.new(vote_params)
      if @vote.save
        redirect_to web_vote_path(@vote), notice: 'Vote was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /votes/1
  def update
    if user_signed_in?
      if @vote.update(vote_params)
        redirect_to web_vote_path(@vote), notice: 'Vote was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /votes/1
  def destroy
    if user_signed_in?
      @vote.destroy
      redirect_to web_votes_url, notice: 'Vote was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:report_id, :user_id, :direction)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/web/votes/_form.html.erb
<%= form_for [:web, vote] do |f| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report %>
    <%= f.select :report_id, Report.all.collect {|c| [ c.description, c.id ] } %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.select :user_id, User.all.collect {|c| [ c.email, c.id ] } %>
  </div>

  <div class="field">
    <%= f.label :direction %>
    <%= f.text_field :direction %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web/votes/edit.html.erb
<h1 class="text-center">Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', web_vote_path(@vote) %> |
<%= link_to 'Back', web_votes_path %>

app/views/web/votes/index.html.erb
<h1 class="text-center">Votes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Report</th>
      <th>User</th>
      <th>Direction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.report.description %></td>
        <td><%= vote.user.email %></td>
        <td><%= vote.direction %></td>
        <td><%= link_to 'Show', web_vote_path(vote) %></td>
        <td><%= link_to 'Edit', edit_web_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', web_vote_path(vote), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_web_vote_path %>

app/views/web/votes/new.html.erb
<h1 class="text-center">New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', web_votes_path %>

app/views/web/votes/show.html.erb
<p>
  <strong>Report:</strong>
  <%= @vote.report.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @vote.user.email %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @vote.direction %>
</p>

<%= link_to 'Edit', edit_web_vote_path(@vote) %> |
<%= link_to 'Back', web_votes_path %>