config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'web/reports#index'


  devise_for :users, constraints: {format: :html}, controllers: { registrations: "web/registrations" }
  as :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'

    get 'sign_up', to: 'web/registrations#new'
    get 'cancel',  to: 'web/registrations#cancel'
  end

  namespace :web, defaults: {format: :html}, constraints: {format: :html}, path: '/' do
    root 'reports#index'
    resources :votes,       constraints: {format: :html}
    resources :reports,     constraints: {format: :html}
    resources :issues,      constraints: {format: :html}
    resources :departments, constraints: {format: :html}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [:index, :show]
  end  


  namespace :api, defaults: {format: :json}, constraints: {format: :json}, path: '/api' do
    scope module: :v1 do
  		resources :departments
      resources :issues
      resources :reports
      resources :sessions, only: [:create, :destroy]
      resources :users,    only: [:index, :show]
      resources :votes

    end
  end


end

app/models/department.rb
class Department < ApplicationRecord
	has_many :issues
end

app/controllers/api/v1/departments_controller.rb
class Api::V1::DepartmentsController < ApplicationController
  include Authenticable
  skip_before_action :verify_authenticity_token
  before_action :authenticate_with_token!, only: [:create, :update, :destroy]
  before_action :set_department, only: [:show, :update, :destroy]
  respond_to :json

  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1.json
  def show
  end

  # POST /departments.json
  def create
    @department = Department.new(department_params)
    if @department.save
      render :show, status: :created, location: api_department_url(@department)
    else
      render json: @department.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /departments/1.json
  def update
    if @department.update(department_params)
      render :show, status: :ok, location: api_department_url(@department)
    else
      render json: @department.errors, status: :unprocessable_entity
    end
    
  end

  # DELETE /departments/1.json
  def destroy
    @department.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :email, :phone, :organization)
    end
end

app/controllers/web/departments_controller.rb
class Web::DepartmentsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  layout 'web/layouts/application'
  respond_to :html

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/1
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  def create
    if user_signed_in?
      @department = Department.new(department_params)
      if @department.save
        redirect_to web_department_path(@department), notice: 'Department was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /departments/1
  def update
    if user_signed_in?
      if @department.update(department_params)
        redirect_to web_department_path(@department), notice: 'Department was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /departments/1
  def destroy
    if user_signed_in?
      @department.destroy
      redirect_to web_departments_url, notice: 'Department was successfully destroyed.' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :email, :phone, :organization)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/web/departments/_form.html.erb
<%= form_for [:web, department] do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :organization %>
    <%= f.text_field :organization %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web/departments/edit.html.erb
<h1 class="text-center">Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', web_department_path(@department) %> |
<%= link_to 'Back', web_departments_path %>

app/views/web/departments/index.html.erb
<h1 class="text-center">Departments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.email %></td>
        <td><%= department.phone %></td>
        <td><%= department.organization %></td>
        <td><%= link_to 'Show', web_department_path(department) %></td>
        <td><%= link_to 'Edit', edit_web_department_path(department) %></td>
        <td><%= link_to 'Destroy', web_department_path(department), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_web_department_path %>

app/views/web/departments/new.html.erb
<h1 class="text-center">New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', web_departments_path %>

app/views/web/departments/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @department.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @department.phone %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @department.organization %>
</p>

<%= link_to 'Edit', edit_web_department_path(@department) %> |
<%= link_to 'Back', web_departments_path %>